version: "3.8"


services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0
    container_name: fastapi
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - redis
    restart: always

  redis:
    image: redis:latest
    container_name: redis
    ports:
    - "6379:6379"